### ISSUE TITLE
Feature request - Control Climate entity and note remote

### ISSUE THREAD

**Issue by theone11** [silentbil/silent-remotes-card#2]
Hello,

Love the AC remote design.

Can the card be adapted to control a **climate** entity and not a **remote** entity (like the Thermostat Card or Simple Thermostat Card)?

If yes then the **callServiceProps** and **commandsFilePath** options can be removed in this configuration

Thanks for the great work

**Comment by silentbil** [comment]
Hi @theone11 thanks for the feedback!
I will check to see if possible, and update

Regards

**Comment by silentbil** [comment]
@theone11 can u plz share an example of your climate entity?

**Comment by theone11** [comment]
Currently I am using [this card](https://github.com/nervetattoo/simple-thermostat):

```
type: custom:simple-thermostat
entity: climate.hvac_hallway_virtual_1
show_header: false
decimals: 0
step_size: 1
step_layout: row
hide:
  setpoint: false
  temperature: true
control:
  - hvac
  - fan
layout:
  mode:
    headings: false
```

and it looks like this (black theme)

![image](https://user-images.githubusercontent.com/3348953/231521979-e5fcfd47-3104-46d3-9aeb-caa0d2d54f1d.png)

The climate entity is:

```
climate:
  - platform: smartir
    name: HVAC Hallway Virtual 1
    unique_id: hvac_hallway_virtual1
    device_code: 1621
    controller_data: remote.hallway_remote
    delay: 10
```

I would like to keep this existing climate entity and have your card just load the temperature, fan speed, mode, on/off into the climate entity.

From there the climate entity will activate the remote as it does now.

**Comment by silentbil** [comment]
Hi @theone11 
got something for you, i hope it will work!

u can now simply pass the entity, example:
```
type: custom:silent-remotes-card
theme: light
title: Electra
remoteType: ac
entity: climate.salon_ac
```

dont forget to upgrade first.
plz let me know if it worked
Thanks

**Comment by theone11** [comment]
It is working **great**. Thanks.

Can I add another request?

The current mode options are **Cool** and **Heat**. Can you add **OFF** and **Auto** --> mode button cycles through **OFF, Cool, Heat, Auto**

and an option to hide the ON OFF buttons?

I want to use your card as a scheduler control so the ON and OFF buttons are redundant because the Cool,Heat,Auto actually turn ON the HVAC.

**Comment by silentbil** [comment]
> It is working **great**. Thanks.
> 
> Can I add another request?
> 
> The current mode options are **Cool** and **Heat**. Can you add **OFF** and **Auto** --> mode button cycles through **OFF, Cool, Heat, Auto**
> 
> and an option to hide the ON OFF buttons?
> 
> I want to use your card as a scheduler control so the ON and OFF buttons are redundant because the Cool,Heat,Auto actually turn ON the HVAC.

Thanks for the update!

just to verify - if i remove the on button (optional)
and lets say the remote display cool mode, but the ac is actually off right now,
u will need to press the mode 4 times (going heat, auto, off , cool again) to turn on.
i was trying to avoid it by adding those quick "on" "off" buttons.

**Comment by theone11** [comment]
I understand that, but because I use this as a virtual climate entity (temporary), of which I have 4, I don't need to actually turn on the AC directly with it.
I have an automation that when the set time occurs the data (mode, temperature, fan mode) from this climate entity is copied into the "real" climate entity and that is what controls the AC.

![image](https://user-images.githubusercontent.com/3348953/235376220-1e8b3d58-fda0-4e6e-9dc7-e4e328c27ac4.png)

Blueprint for the automation:
```
blueprint:
  name: HVAC Scheduler
  description: Set the temperature, fan_mode and mode of the HVAC at a specific time
  domain: automation
  input:
    start_time:
      name: Start Time
      description: Trigger - The time the automation should start
      selector:
        entity:
          domain: input_datetime
    scheduler_enable:
      name: Scheduler Enable
      description: Condition - Enable the scheduler if 'on' (Must have 'on' state to work)
      selector:
        entity:
          domain: input_boolean
    virtual_climate:
      name: Virtual Climate
      description: The Climate entity from which the automation takes the HVAC settings
      selector:
        entity:
          domain: climate
    target_climate:
      name: Target Climate
      description: The target Climate entity that controls the actual HVAC
      selector:
        entity:
          domain: climate
mode: restart
max_exceeded: silent
variables:
  virtual_climate: !input virtual_climate
  scheduler_enable: !input scheduler_enable
trigger:
  platform: time
  at: !input start_time
condition:
  - condition: state
    entity_id: !input scheduler_enable
    state: "on"
action:
  - service: notify.file_debug
    data:
      message: "{{ this.attributes.friendly_name }} - {{ states(scheduler_enable) }} - {{ state_attr(virtual_climate, 'temperature') }}/{{ state_attr(virtual_climate, 'fan_mode') }}/{{ states(virtual_climate) }}"
  - service: climate.set_fan_mode
    data:
      entity_id: !input target_climate
      fan_mode: "{{ state_attr(virtual_climate, 'fan_mode') }}"
  - service: climate.set_temperature
    data:
      entity_id: climate.hvac_hallway
      temperature: "{{ state_attr(virtual_climate, 'temperature') | float }}"
      hvac_mode: "{{ states(virtual_climate) }}"
  - service: input_boolean.turn_off
    entity_id: !input scheduler_enable
```
